export declare const MIN_WINDOW_WIDTH = 200;
export declare const MIN_WINDOW_HEIGHT = 100;
export declare const MAX_WINDOWS = 20;
export declare const WINDOW_BASE_Z = 100;
export declare const MODAL_BASE_Z = 500;
export declare const TASKBAR_Z = 1000;
export declare const START_MENU_Z = 1100;
export declare const TASKBAR_HEIGHT = 28;
export declare const TITLEBAR_HEIGHT = 24;
export declare const WINDOW_BORDER_WIDTH = 2;
export declare const STORAGE_KEY = "abu-os-98:state:v1";
export declare const STORAGE_VERSION = 1;
export declare const STORAGE_TTL_DAYS = 7;
export declare const STORAGE_DEBOUNCE_MS = 500;
export declare const DRAG_DEBOUNCE_MS = 16;
export declare const DEFAULT_WINDOW_WIDTH = 600;
export declare const DEFAULT_WINDOW_HEIGHT = 400;
export declare const DESKTOP_ICON_SIZE = 48;
export declare const DESKTOP_ICON_SPACING = 16;
export declare const DESKTOP_GRID_COLUMNS = 8;
export declare const VOLUME_MIN = 0;
export declare const VOLUME_MAX = 1;
export declare const VOLUME_DEFAULT = 0.5;
export declare const DEFAULT_THEME: "light";
export declare const WINDOW_RESIZE_HANDLES: readonly ["n", "ne", "e", "se", "s", "sw", "w", "nw"];
export declare const SUPPORTED_THEMES: readonly ["light", "dark"];
